cd ~/dropbox
import excel "P_Data_Extract_From_World_Development_Indicators.xlsx", sheet("Data") firstrow clear
tempfile tfile

foreach i of var E-BQ {
	local temp : var label `i'
	rename `i' v`temp'
}

levelsof CountryCode, local(cset)
preserve
local itr = 1
    foreach j of local cset {
        keep if CountryCode == "`j'" 
        local cclv = CountryName[1]
        qui count
        local vmax = r(N)
        forvalue i = 1/`vmax' {
            local vc`i' = SeriesCode[`i'] 
            local vl`i' = SeriesName[`i']
        }
        xpose , clear
        drop in 1/4
        forvalue i = 1/`vmax' {
            label var v`i' "`vl`i''"
        }
        gen ccode = "`j'"
            label var ccode "ISO3 Country Code"
        gen cname = "`cclv'"
            label var cname "Country Name"
        gen year = _n + 1959
            label var year "Year"
        if `itr' == 1 {
            save `tfile' , replace
        }
        else  {
            append using `tfile'
            save `tfile' , replace
        }
        restore , preserve
        local ++itr
    }

use `tfile' , clear
compress
/*gen isc{{{*/
gen isc = regexm(ccode, "^[A-Z]{3}$")
    replace isc = 0 if inlist(ccode,"WLD","SSA","SSF","ARB","OED","EMU","EUU") ///
    | inlist(ccode,"NAC","LCN","LAC","IDA","IBD","IBT","IDX","IDB") ///
    | inlist(ccode,"UMC","LMC","LIC","MIC","LMY")
    label var isc "Country Dummy"
    replace isc = 0 if cname == "Africa Eastern and Southern"
    replace isc = 0 if cname == "Caribbean small states"
    replace isc = 0 if cname == "East Asia & Pacific (excluding high income)"
    replace isc = 0 if cname == "Europe & Central Asia (excluding high income)"
    replace isc = 0 if cname == "Heavily indebted poor countries (HIPC)"
    replace isc = 0 if cname == "IDA only"
    replace isc = 0 if cname == "Latin America & Caribbean"
    replace isc = 0 if cname == "Least developed countries: UN classification"
    replace isc = 0 if cname == "Middle East, North Africa, Afghanistan & Pakistan (excluding high income)"
    replace isc = 0 if cname == "OECD members"
    replace isc = 0 if cname == "Post-demographic dividend"
    replace isc = 0 if cname == "Africa Western and Central"
    replace isc = 0 if cname == "Central Europe and the Baltics"
    replace isc = 0 if cname == "East Asia & Pacific (IDA & IBRD countries)"
    replace isc = 0 if cname == "Europe & Central Asia (IDA & IBRD countries)"
    replace isc = 0 if cname == "High income"
    replace isc = 0 if cname == "IDA & IBRD total"
    replace isc = 0 if cname == "IDAtotal"
    replace isc = 0 if cname == "Latin America & Caribbean (excluding high income)"
    replace isc = 0 if cname == "Low & middle income"
    replace isc = 0 if cname == "Lower middle income"
    replace isc = 0 if cname == "Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)"
    replace isc = 0 if cname == "Other small states"
    replace isc = 0 if cname == "Pre-demographic dividend"
    replace isc = 0 if cname == "Arab World"
    replace isc = 0 if cname == "Early-demographic dividend"
    replace isc = 0 if cname == "East Asia & Pacific"
    replace isc = 0 if cname == "Euro area"
    replace isc = 0 if cname == "Europe & Central Asia"
    replace isc = 0 if cname == "European Union"
    replace isc = 0 if cname == "Fragile and conflict affected situations"
    replace isc = 0 if cname == "IBRD only"
    replace isc = 0 if cname == "IDA blend"
    replace isc = 0 if cname == "Late-demographic dividend"
    replace isc = 0 if cname == "Latin America & the Caribbean (IDA & IBRD countries)"
    replace isc = 0 if cname == "Low income"
    replace isc = 0 if cname == "Middle East, North Africa, Afghanistan & Pakistan"
    replace isc = 0 if cname == "Middle income"
    replace isc = 0 if cname == "North America"
    replace isc = 0 if cname == "Not classified"
    replace isc = 0 if cname == "Pacific island small states"
    replace isc = 0 if cname == "Small states"
    replace isc = 0 if cname == "Middle East, North Africa, Afghanistan & Pakistan"
    replace isc = 0 if cname == "Europe & Central Asia"
    replace isc = 0 if cname == "East Asia & Pacific"
    replace isc = 0 if cname == "Sub-Saharan Africa"
    replace isc = 0 if cname == "Latin America & Caribbean"
    replace isc = 0 if cname == "South Asia"
    replace isc = 0 if cname == "North America"
    replace isc = 0 if cname == "Low income"
    replace isc = 0 if cname == "Upper middle income"
    replace isc = 0 if cname == "High income"
    replace isc = 0 if cname == "Lower middle income"
    replace isc = 0 if cname == "Not classified"
    replace isc = 0 if cname == "IDA"
    replace isc = 0 if cname == "IBRD"
    replace isc = 0 if cname == "Not classified"
    replace isc = 0 if cname == "Blend"
    replace isc = 0 if cname == "South Asia"
    replace isc = 0 if cname == "South Asia (IDA & IBRD)"
    replace isc = 0 if cname == "Sub-Saharan Africa"
    replace isc = 0 if cname == "Sub-Saharan Africa (excluding high income)"
    replace isc = 0 if cname == "Sub-Saharan Africa (IDA & IBRD countries)"
    replace isc = 0 if cname == "Upper middle income"
/*}}}*/
/*gen ctt{{{*/
    gen str20 ctt = ""
    * Africa
    local AFR "DZA AGO BWA BDI CMR CAF TCD COM COG COD DJI EGY GNQ ERI ETH GAB GMB GHA GIN GNB KEN LSO LBR LBY MDG MWI MLI MRT MUS MAR MOZ NAM NER NGA RWA STP SEN SYC SLE ZAF SSD SDN SWZ TGO TUN UGA TZA ZMB ZWE"
    foreach c of local AFR {
        replace ctt = "Africa" if ccode == "`c'"
    }
    * Asia
    local ASIA "AFG ARM AZE BHR BGD BTN BRN KHM CHN GEO IND IDN IRN IRQ ISR JPN JOR KAZ KWT KGZ LAO LBN MAC MYS MDV MNG MMR NPL PRK OMN PAK PSE PHL QAT SAU SGP KOR LKA SYR TWN TJK THA TUR TKM ARE UZB VNM YEM"
    foreach c of local ASIA {
        replace ctt = "Asia" if ccode == "`c'"
    }
    * Europe
    local EUR "ALB AND AUT BLR BEL BIH BGR HRV CYP CZE DNK EST FIN FRA DEU GRC HUN ISL IRL ITA XKX LVA LIE LTU LUX MLT MDA MCO MNE NLD MKD NOR POL PRT ROU RUS SMR SRB SVK SVN ESP SWE CHE UKR GBR"
    foreach c of local EUR {
        replace ctt = "Europe" if ccode == "`c'"
    }
    * North America
    local NAM "CAN USA MEX BLZ GTM HND NIC CRI PAN"
    foreach c of local NAM {
        replace ctt = "North America" if ccode == "`c'"
    }
    * South America
    local SAM "ARG BOL BRA CHL COL ECU PRY PER SUR URY VEN GUY"
    foreach c of local SAM {
        replace ctt = "South America" if ccode == "`c'"
    }
    * Oceania
    local OCE "AUS FJI KIR MHL FSM NRU NZL PLW PNG WSM SLB TON TUV VUT"
    foreach c of local OCE {
        replace ctt = "Oceania" if ccode == "`c'"
    }
    * Caribbean
    local CAR "ATG BHS BRB CUB DMA DOM GRD HTI JAM KNA LCA VCT TTO ABW AIA BMU CYM CUW GLP MTQ PRI SXM TCA VIR"
    foreach c of local CAR {
        replace ctt = "Caribbean" if ccode == "`c'"
    }
    label var ctt "Continent"
/*}}}*/
/*gen kname{{{*/
    gen kname = ""
    label var kname "Country Name in Korean"
    replace kname = "아프가니스탄"           if cname == "Afghanistan"
    replace kname = "알바니아"               if cname == "Albania"
    replace kname = "알제리"                 if cname == "Algeria"
    replace kname = "아메리칸사모아"         if cname == "American Samoa"
    replace kname = "안도라"                 if cname == "Andorra"
    replace kname = "앙골라"                 if cname == "Angola"
    replace kname = "안티구아 바부다"        if cname == "Antigua and Barbuda"
    replace kname = "아르헨티나"             if cname == "Argentina"
    replace kname = "아르메니아"             if cname == "Armenia"
    replace kname = "아루바"                 if cname == "Aruba"
    replace kname = "호주"                   if cname == "Australia"
    replace kname = "오스트리아"             if cname == "Austria"
    replace kname = "아제르바이잔"           if cname == "Azerbaijan"
    replace kname = "바하마"                 if cname == "Bahamas, The"
    replace kname = "바레인"                 if cname == "Bahrain"
    replace kname = "방글라데시"             if cname == "Bangladesh"
    replace kname = "바베이도스"             if cname == "Barbados"
    replace kname = "벨라루스"               if cname == "Belarus"
    replace kname = "벨기에"                 if cname == "Belgium"
    replace kname = "벨리즈"                 if cname == "Belize"
    replace kname = "베냉"                   if cname == "Benin"
    replace kname = "버뮤다"                 if cname == "Bermuda"
    replace kname = "부탄"                   if cname == "Bhutan"
    replace kname = "볼리비아"               if cname == "Bolivia"
    replace kname = "보스니아 헤르체고비나"  if cname == "Bosnia and Herzegovina"
    replace kname = "보츠와나"               if cname == "Botswana"
    replace kname = "브라질"                 if cname == "Brazil"
    replace kname = "영국령 버진아일랜드"    if cname == "British Virgin Islands"
    replace kname = "브루나이"               if cname == "Brunei Darussalam"
    replace kname = "불가리아"               if cname == "Bulgaria"
    replace kname = "부르키나파소"           if cname == "Burkina Faso"
    replace kname = "부룬디"                 if cname == "Burundi"
    replace kname = "카보베르데"             if cname == "Cabo Verde"
    replace kname = "캄보디아"               if cname == "Cambodia"
    replace kname = "카메룬"                 if cname == "Cameroon"
    replace kname = "캐나다"                 if cname == "Canada"
    replace kname = "케이맨 제도"            if cname == "Cayman Islands"
    replace kname = "중앙아프리카공화국"     if cname == "Central African Republic"
    replace kname = "차드"                   if cname == "Chad"
    replace kname = "채널 제도"              if cname == "Channel Islands"
    replace kname = "칠레"                   if cname == "Chile"
    replace kname = "중국"                   if cname == "China"
    replace kname = "콜롬비아"               if cname == "Colombia"
    replace kname = "코모로"                 if cname == "Comoros"
    replace kname = "콩고민주공화국"         if cname == "Congo, Dem. Rep."
    replace kname = "콩고공화국"             if cname == "Congo, Rep."
    replace kname = "코스타리카"             if cname == "Costa Rica"
    replace kname = "코트디부아르"           if cname == "Cote d'Ivoire"
    replace kname = "크로아티아"             if cname == "Croatia"
    replace kname = "쿠바"                   if cname == "Cuba"
    replace kname = "퀴라소"                 if cname == "Curacao"
    replace kname = "키프로스"               if cname == "Cyprus"
    replace kname = "체코"                   if cname == "Czechia"
    replace kname = "덴마크"                 if cname == "Denmark"
    replace kname = "지부티"                 if cname == "Djibouti"
    replace kname = "도미니카"               if cname == "Dominica"
    replace kname = "도미니카공화국"         if cname == "Dominican Republic"
    replace kname = "에콰도르"               if cname == "Ecuador"
    replace kname = "이집트"                 if cname == "Egypt, Arab Rep."
    replace kname = "엘살바도르"             if cname == "El Salvador"
    replace kname = "적도 기니"              if cname == "Equatorial Guinea"
    replace kname = "에리트레아"             if cname == "Eritrea"
    replace kname = "에스토니아"             if cname == "Estonia"
    replace kname = "에스와티니"             if cname == "Eswatini"
    replace kname = "에티오피아"             if cname == "Ethiopia"
    replace kname = "페로 제도"              if cname == "Faroe Islands"
    replace kname = "피지"                   if cname == "Fiji"
    replace kname = "핀란드"                 if cname == "Finland"
    replace kname = "프랑스"                 if cname == "France"
    replace kname = "프랑스령 폴리네시아"    if cname == "French Polynesia"
    replace kname = "가봉"                   if cname == "Gabon"
    replace kname = "감비아"                 if cname == "Gambia, The"
    replace kname = "조지아"                 if cname == "Georgia"
    replace kname = "독일"                   if cname == "Germany"
    replace kname = "가나"                   if cname == "Ghana"
    replace kname = "지브롤터"               if cname == "Gibraltar"
    replace kname = "그리스"                 if cname == "Greece"
    replace kname = "그린란드"               if cname == "Greenland"
    replace kname = "그레나다"               if cname == "Grenada"
    replace kname = "괌"                     if cname == "Guam"
    replace kname = "과테말라"               if cname == "Guatemala"
    replace kname = "기니"                   if cname == "Guinea"
    replace kname = "기니비사우"             if cname == "Guinea-Bissau"
    replace kname = "가이아나"               if cname == "Guyana"
    replace kname = "아이티"                 if cname == "Haiti"
    replace kname = "온두라스"               if cname == "Honduras"
    replace kname = "홍콩"                   if cname == "Hong Kong SAR, China"
    replace kname = "헝가리"                 if cname == "Hungary"
    replace kname = "아이슬란드"             if cname == "Iceland"
    replace kname = "인도"                   if cname == "India"
    replace kname = "인도네시아"             if cname == "Indonesia"
    replace kname = "이란"                   if cname == "Iran, Islamic Rep."
    replace kname = "이라크"                 if cname == "Iraq"
    replace kname = "아일랜드"               if cname == "Ireland"
    replace kname = "맨섬"                   if cname == "Isle of Man"
    replace kname = "이스라엘"               if cname == "Israel"
    replace kname = "이탈리아"               if cname == "Italy"
    replace kname = "자메이카"               if cname == "Jamaica"
    replace kname = "일본"                   if cname == "Japan"
    replace kname = "요르단"                 if cname == "Jordan"
    replace kname = "카자흐스탄"             if cname == "Kazakhstan"
    replace kname = "케냐"                   if cname == "Kenya"
    replace kname = "키리바시"               if cname == "Kiribati"
    replace kname = "북한"                   if cname == "Korea, Dem. People's Rep."
    replace kname = "대한민국"               if cname == "Korea, Rep."
    replace kname = "코소보"                 if cname == "Kosovo"
    replace kname = "쿠웨이트"               if cname == "Kuwait"
    replace kname = "키르기스스탄"           if cname == "Kyrgyz Republic"
    replace kname = "라오스"                 if cname == "Lao PDR"
    replace kname = "라트비아"               if cname == "Latvia"
    replace kname = "레바논"                 if cname == "Lebanon"
    replace kname = "레소토"                 if cname == "Lesotho"
    replace kname = "라이베리아"             if cname == "Liberia"
    replace kname = "리비아"                 if cname == "Libya"
    replace kname = "리히텐슈타인"           if cname == "Liechtenstein"
    replace kname = "리투아니아"             if cname == "Lithuania"
    replace kname = "룩셈부르크"             if cname == "Luxembourg"
    replace kname = "마카오"                 if cname == "Macao SAR, China"
    replace kname = "마다가스카르"           if cname == "Madagascar"
    replace kname = "말라위"                 if cname == "Malawi"
    replace kname = "말레이시아"             if cname == "Malaysia"
    replace kname = "몰디브"                 if cname == "Maldives"
    replace kname = "말리"                   if cname == "Mali"
    replace kname = "몰타"                   if cname == "Malta"
    replace kname = "마셜 제도"              if cname == "Marshall Islands"
    replace kname = "모리타니"               if cname == "Mauritania"
    replace kname = "모리셔스"               if cname == "Mauritius"
    replace kname = "멕시코"                 if cname == "Mexico"
    replace kname = "미크로네시아 연방"      if cname == "Micronesia, Fed. Sts."
    replace kname = "몰도바"                 if cname == "Moldova"
    replace kname = "모나코"                 if cname == "Monaco"
    replace kname = "몽골"                   if cname == "Mongolia"
    replace kname = "몬테네그로"             if cname == "Montenegro"
    replace kname = "모로코"                 if cname == "Morocco"
    replace kname = "모잠비크"               if cname == "Mozambique"
    replace kname = "미얀마"                 if cname == "Myanmar"
    replace kname = "나미비아"               if cname == "Namibia"
    replace kname = "나우루"                 if cname == "Nauru"
    replace kname = "네팔"                   if cname == "Nepal"
    replace kname = "네덜란드"               if cname == "Netherlands"
    replace kname = "뉴칼레도니아"           if cname == "New Caledonia"
    replace kname = "뉴질랜드"               if cname == "New Zealand"
    replace kname = "니카라과"               if cname == "Nicaragua"
    replace kname = "니제르"                 if cname == "Niger"
    replace kname = "나이지리아"             if cname == "Nigeria"
    replace kname = "북마케도니아"           if cname == "North Macedonia"
    replace kname = "북마리아나 제도"        if cname == "Northern Mariana Islands"
    replace kname = "노르웨이"               if cname == "Norway"
    replace kname = "오만"                   if cname == "Oman"
    replace kname = "파키스탄"               if cname == "Pakistan"
    replace kname = "팔라우"                 if cname == "Palau"
    replace kname = "파나마"                 if cname == "Panama"
    replace kname = "파푸아뉴기니"           if cname == "Papua New Guinea"
    replace kname = "파라과이"               if cname == "Paraguay"
    replace kname = "페루"                   if cname == "Peru"
    replace kname = "필리핀"                 if cname == "Philippines"
    replace kname = "키리바시"               if cname == "Kiribati"
    replace kname = "북한"                   if cname == "Korea, Dem. People's Rep."
    replace kname = "대한민국"               if cname == "Korea, Rep."
    replace kname = "코소보"                 if cname == "Kosovo"
    replace kname = "쿠웨이트"               if cname == "Kuwait"
    replace kname = "키르기스스탄"           if cname == "Kyrgyz Republic"
    replace kname = "라오스"                 if cname == "Lao PDR"
    replace kname = "라트비아"               if cname == "Latvia"
    replace kname = "레바논"                 if cname == "Lebanon"
    replace kname = "레소토"                 if cname == "Lesotho"
    replace kname = "라이베리아"             if cname == "Liberia"
    replace kname = "리비아"                 if cname == "Libya"
    replace kname = "리히텐슈타인"           if cname == "Liechtenstein"
    replace kname = "리투아니아"             if cname == "Lithuania"
    replace kname = "룩셈부르크"             if cname == "Luxembourg"
    replace kname = "마카오"                 if cname == "Macao SAR, China"
    replace kname = "마다가스카르"           if cname == "Madagascar"
    replace kname = "말라위"                 if cname == "Malawi"
    replace kname = "말레이시아"             if cname == "Malaysia"
    replace kname = "몰디브"                 if cname == "Maldives"
    replace kname = "말리"                   if cname == "Mali"
    replace kname = "몰타"                   if cname == "Malta"
    replace kname = "마셜 제도"              if cname == "Marshall Islands"
    replace kname = "모리타니"               if cname == "Mauritania"
    replace kname = "모리셔스"               if cname == "Mauritius"
    replace kname = "멕시코"                 if cname == "Mexico"
    replace kname = "미크로네시아 연방"      if cname == "Micronesia, Fed. Sts."
    replace kname = "몰도바"                 if cname == "Moldova"
    replace kname = "모나코"                 if cname == "Monaco"
    replace kname = "몽골"                   if cname == "Mongolia"
    replace kname = "몬테네그로"             if cname == "Montenegro"
    replace kname = "모로코"                 if cname == "Morocco"
    replace kname = "모잠비크"               if cname == "Mozambique"
    replace kname = "미얀마"                 if cname == "Myanmar"
    replace kname = "나미비아"               if cname == "Namibia"
    replace kname = "나우루"                 if cname == "Nauru"
    replace kname = "네팔"                   if cname == "Nepal"
    replace kname = "네덜란드"               if cname == "Netherlands"
    replace kname = "뉴칼레도니아"           if cname == "New Caledonia"
    replace kname = "뉴질랜드"               if cname == "New Zealand"
    replace kname = "니카라과"               if cname == "Nicaragua"
    replace kname = "니제르"                 if cname == "Niger"
    replace kname = "나이지리아"             if cname == "Nigeria"
    replace kname = "북마케도니아"           if cname == "North Macedonia"
    replace kname = "북마리아나 제도"        if cname == "Northern Mariana Islands"
    replace kname = "노르웨이"               if cname == "Norway"
    replace kname = "오만"                   if cname == "Oman"
    replace kname = "파키스탄"               if cname == "Pakistan"
    replace kname = "팔라우"                 if cname == "Palau"
    replace kname = "파나마"                 if cname == "Panama"
    replace kname = "파푸아뉴기니"           if cname == "Papua New Guinea"
    replace kname = "파라과이"               if cname == "Paraguay"
    replace kname = "페루"                   if cname == "Peru"
    replace kname = "필리핀"                 if cname == "Philippines"
    replace kname = "폴란드"                 if cname == "Poland"
    replace kname = "포르투갈"               if cname == "Portugal"
    replace kname = "푸에르토리코"           if cname == "Puerto Rico (US)"
    replace kname = "카타르"                 if cname == "Qatar"
    replace kname = "루마니아"               if cname == "Romania"
    replace kname = "러시아"                 if cname == "Russian Federation"
    replace kname = "르완다"                 if cname == "Rwanda"
    replace kname = "사모아"                 if cname == "Samoa"
    replace kname = "산마리노"               if cname == "San Marino"
    replace kname = "상투메 프린시페"        if cname == "Sao Tome and Principe"
    replace kname = "사우디아라비아"         if cname == "Saudi Arabia"
    replace kname = "세네갈"                 if cname == "Senegal"
    replace kname = "세르비아"               if cname == "Serbia"
    replace kname = "세이셸"                 if cname == "Seychelles"
    replace kname = "시에라리온"             if cname == "Sierra Leone"
    replace kname = "싱가포르"               if cname == "Singapore"
    replace kname = "신트마르턴(네덜란드령)" if cname == "Sint Maarten (Dutch part)"
    replace kname = "슬로바키아"             if cname == "Slovak Republic"
    replace kname = "슬로베니아"             if cname == "Slovenia"
    replace kname = "솔로몬 제도"            if cname == "Solomon Islands"
    replace kname = "소말리아"               if cname == "Somalia"
    replace kname = "남아프리카공화국"       if cname == "South Africa"
    replace kname = "남수단"                 if cname == "South Sudan"
    replace kname = "스페인"                 if cname == "Spain"
    replace kname = "스리랑카"               if cname == "Sri Lanka"
    replace kname = "세인트키츠 네비스"      if cname == "St. Kitts and Nevis"
    replace kname = "세인트루시아"           if cname == "St. Lucia"
    replace kname = "세인트마르틴(프랑스령)" if cname == "St. Martin (French part)"
    replace kname = "세인트빈센트 그레나딘"  if cname == "St. Vincent and the Grenadines"
    replace kname = "수단"                   if cname == "Sudan"
    replace kname = "수리남"                 if cname == "Suriname"
    replace kname = "스웨덴"                 if cname == "Sweden"
    replace kname = "스위스"                 if cname == "Switzerland"
    replace kname = "시리아"                 if cname == "Syrian Arab Republic"
    replace kname = "타지키스탄"             if cname == "Tajikistan"
    replace kname = "탄자니아"               if cname == "Tanzania"
    replace kname = "태국"                   if cname == "Thailand"
    replace kname = "동티모르"               if cname == "Timor-Leste"
    replace kname = "토고"                   if cname == "Togo"
    replace kname = "통가"                   if cname == "Tonga"
    replace kname = "트리니다드 토바고"      if cname == "Trinidad and Tobago"
    replace kname = "튀니지"                 if cname == "Tunisia"
    replace kname = "튀르키예"               if cname == "Turkiye"
    replace kname = "투르크메니스탄"         if cname == "Turkmenistan"
    replace kname = "터크스 케이커스 제도"   if cname == "Turks and Caicos Islands"
    replace kname = "투발루"                 if cname == "Tuvalu"
    replace kname = "우간다"                 if cname == "Uganda"
    replace kname = "우크라이나"             if cname == "Ukraine"
    replace kname = "아랍에미리트"           if cname == "United Arab Emirates"
    replace kname = "영국"                   if cname == "United Kingdom"
    replace kname = "미국"                   if cname == "United States"
    replace kname = "우루과이"               if cname == "Uruguay"
    replace kname = "우즈베키스탄"           if cname == "Uzbekistan"
    replace kname = "바누아투"               if cname == "Vanuatu"
    replace kname = "베네수엘라"             if cname == "Venezuela, RB"
    replace kname = "베트남"                 if cname == "Viet Nam"
    replace kname = "미국령 버진아일랜드"    if cname == "Virgin Islands (U.S.)"
    replace kname = "서안과 가자지구"        if cname == "West Bank and Gaza"
    replace kname = "예멘"                   if cname == "Yemen, Rep."
    replace kname = "잠비아"                 if cname == "Zambia"
    replace kname = "짐바브웨"               if cname == "Zimbabwe"
/*}}}*/
sort cname year
order ccode isc ccode ctt cname kname year , first
label data "World Development Index from World Bank"
save wdi , replace
