label var year   "년도"
label var dtfive "5분위배율(가계동향,가처분소득)"
label var dtgini "지니계수(가계동향,가처분소득) "
label var dtpvty "빈곤율(가계동향,가처분소득)"
label var dwfive "5분위배율(가금복,가처분소득)"
label var dwgini "지니계수(가금복,가처분소득)"
label var dwpvty "빈곤율(가금복,가처분소득)"
label var mtgini "지니계수(가계동향,시장소득)"
label var mtpvty "빈곤율(가계동향,시장소득)"
label var mwgini "지니계수(가금복,시장소득)"
label var mwpvty "빈곤율(가금복,시장소득)"
